name: myapp
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^5.4.3
  cupertino_icons: ^1.0.8
  http: ^1.0.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.1
  flutter_map_directions: ^0.0.5
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.3
  firebase_database: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Uncomment and add assets if needed
  assets:
  - assets/images/
flutter_native_splash:
  color: "#ffffff" # Background color for splash screen
  image: assets/images/Asset 2.png # Path to your splash image
  android: true
  ios: true

  # Uncomment and configure fonts if needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
