name: myapp
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^5.4.3
  cupertino_icons: ^1.0.8
  http: ^1.0.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.1
  flutter_map_directions: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Uncomment and add assets if needed
  assets:
  - assets/images/

  # Uncomment and configure fonts if needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
