// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRsUZ_eSwPBE5vWJFal-aTGobZB0st1oc',
    appId: '1:291794812913:android:9da43fd28323a5fe840e50',
    messagingSenderId: '291794812913',
    projectId: 'smart-bike-system-7565b',
    storageBucket: 'smart-bike-system-7565b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9-8FtX4fENM7CqlWKCuac_ZY4SyLVjtw',
    appId: '1:291794812913:ios:060303c88f1f2b57840e50',
    messagingSenderId: '291794812913',
    projectId: 'smart-bike-system-7565b',
    storageBucket: 'smart-bike-system-7565b.firebasestorage.app',
    iosBundleId: 'com.example.smartBikeSystem',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ18_0ZHMIuIrEhQNP3XC7HffMMvyjZYM',
    appId: '1:291794812913:web:32f2c80a9dfd2959840e50',
    messagingSenderId: '291794812913',
    projectId: 'smart-bike-system-7565b',
    authDomain: 'smart-bike-system-7565b.firebaseapp.com',
    storageBucket: 'smart-bike-system-7565b.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9-8FtX4fENM7CqlWKCuac_ZY4SyLVjtw',
    appId: '1:291794812913:ios:060303c88f1f2b57840e50',
    messagingSenderId: '291794812913',
    projectId: 'smart-bike-system-7565b',
    storageBucket: 'smart-bike-system-7565b.firebasestorage.app',
    iosBundleId: 'com.example.smartBikeSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ18_0ZHMIuIrEhQNP3XC7HffMMvyjZYM',
    appId: '1:291794812913:web:398f6fd654f25488840e50',
    messagingSenderId: '291794812913',
    projectId: 'smart-bike-system-7565b',
    authDomain: 'smart-bike-system-7565b.firebaseapp.com',
    storageBucket: 'smart-bike-system-7565b.firebasestorage.app',
  );

}